#!/bin/sh

git log -1 "--pretty=format:(Codename: That is Not True) %ci / %H" >OpenSim/Framework/Servers/versioninfo.txt
git log -1 "--pretty=format:OpenSim Arriba (Codename: That is Not True) %ci / %H" >bin/.version
